### ISSUE TITLE
error's when "finishing the mint"

### ISSUE THREAD

**Issue by mattjaf** [PatrickAlphaC/all-on-chain-generated-nft#25] opened 2022-03-12 07:13 UTC
```
PS C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft> yarn hardhat deploy --network rinkeby

yarn run v1.22.15
$ C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\.bin\hardhat deploy --network rinkeby
Nothing to compile
----------------------------------------------------
reusing "SVGNFT" at 0xAD4B9c2783dE05d441Fa0b024a9E1394aF4B2533
You have deployed an NFT contract to 0xAD4B9c2783dE05d441Fa0b024a9E1394aF4B2533
Verify with:
 npx hardhat verify --network rinkeby 0xAD4B9c2783dE05d441Fa0b024a9E1394aF4B2533
Let's create an NFT now!
We will use ./img/small_enough.svg as our SVG, and this will turn into a tokenURI.
You've made your first NFT!
You can view the tokenURI here data:application/json;base64,eyJuYW1lIjoiU1ZHIE5GVCIsICJkZXNjcmlwdGlvbiI6IkFuIE5GVCBiYXNlZCBvbiBTVkchIiwgImF0dHJpYnV0ZXMiOiIiLCAiaW1hZ2UiOiJkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJR2hsYVdkb2REMGlOVEF3SWlCM2FXUjBhRDBpTlRBd0lqNE5DaUFnUEdOcGNtTnNaU0JqZUQwaU1qVXdJaUJqZVQwaU1qVXdJaUJ5UFNJeU1EQWlJSE4wY205clpUMGlZbXhoWTJzaUlITjBjbTlyWlMxM2FXUjBhRDBpTXlJZ1ptbHNiRDBpWW14MVpTSWdMejRnRFFvOEwzTjJaejRnIn0=
----------------------------------------------------
reusing "RandomSVG" at 0x50d60Bd20D5fd1baAF55f7CAeA5716108A25f915
You have deployed an NFT contract to 0x50d60Bd20D5fd1baAF55f7CAeA5716108A25f915
Verify with:
 npx hardhat verify --network rinkeby 0x50d60Bd20D5fd1baAF55f7CAeA5716108A25f915 0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B 0x01be23585060835e02b77ef475b0cc51aa1e0709 0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311 100000000000000000
Duplicate definition of Transfer (Transfer(address,address,uint256,bytes), Transfer(address,address,uint256))
Let's create an NFT now!
You've made your NFT! This is number 0x0000000000000000000000000000000000000000000000000000000000000001
Let's wait for the Chainlink VRF node to respond...
You can view the tokenURI here data:application/json;base64,eyJuYW1lIjoiU1ZHIE5GVCIsICJkZXNjcmlwdGlvbiI6IkFuIE5GVCBiYXNlZCBvbiBTVkchIiwgImF0dHJpYnV0ZXMiOiIiLCAiaW1hZ2UiOiJkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MG5hSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY25JR2hsYVdkb2REMG5OVEF3SnlCM2FXUjBhRDBuTlRBd0p6NDhjR0YwYUNCa1BTZE5JRE00TWlBeE5EWk1JRE16TlNBNU4wMGdNekUwSURNNU5VMGdPVE1nTkRjMkp5Qm1hV3hzUFNkMGNtRnVjM0JoY21WdWRDY2djM1J5YjJ0bFBTZDVaV3hzYjNjbkx6NDhjR0YwYUNCa1BTZE5JREU1TVNBeE9UUk1JREl3TXlBMU5Fd2dOalVnTVRrelRTQXlOekFnTWpBeEp5Qm1hV3hzUFNkMGNtRnVjM0JoY21WdWRDY2djM1J5YjJ0bFBTZDVaV3hzYjNjbkx6NDhjR0YwYUNCa1BTZE1JREV3TkNBME56Sk5JRGt6SURNMU1rd2dOREUxSURJME9DY2dabWxzYkQwbmRISmhibk53WVhKbGJuUW5JSE4wY205clpUMG5ZbXhoWTJzbkx6NDhjR0YwYUNCa1BTZE5JRE16TkNBek16Wk1JRE0zTUNBeE1qSk5JRFF6TXlBME1qSk1JRFE1TlNBeU5UQk5JREV6TnlBeU9UTW5JR1pwYkd3OUozUnlZVzV6Y0dGeVpXNTBKeUJ6ZEhKdmEyVTlKMkpzZFdVbkx6NDhjR0YwYUNCa1BTZE1JRE0wTnlBeU1Ea25JR1pwYkd3OUozUnlZVzV6Y0dGeVpXNTBKeUJ6ZEhKdmEyVTlKM0psWkNjdlBqd3ZjM1puUGc9PSJ9
Now let's finsih the mint...
An unexpected error occurred:

Error: ERROR processing C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\deploy\02_Deploy_RandomSVG.js:
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x3781d6b254e21ac0d6a0ed4b2406f2e3f49d725ac23022907e79021f2306b7ce", transaction={"hash":"0x3781d6b254e21ac0d6a0ed4b2406f2e3f49d725ac23022907e79021f2306b7ce","type":2,"accessList":[],"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0xFc73F357Fb770845063dD42104A6F167fF3aE433","gasPrice":{"type":"BigNumber","hex":"0x59682f0c"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f0c"},"gasLimit":{"type":"BigNumber","hex":"0x1e8480"},"to":"0x50d60Bd20D5fd1baAF55f7CAeA5716108A25f915","value":{"type":"BigNumber","hex":"0x00"},"nonce":275,"data":"0x624194c70000000000000000000000000000000000000000000000000000000000000001","r":"0xe06af8c83e3c7745b4c8c7729e53601b2918bac66668b69b9eed4879e2a94c25","s":"0x7dab70428714257bcbe3be4fb730ad9dade81baebc6e3bfab5171fd26ecabded","v":0,"creates":null,"chainId":4}, receipt={"to":"0x50d60Bd20D5fd1baAF55f7CAeA5716108A25f915","from":"0xFc73F357Fb770845063dD42104A6F167fF3aE433","contractAddress":null,"transactionIndex":24,"gasUsed":{"type":"BigNumber","hex":"0x01b234"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x2700b4b5d87672f4bd4ed4f81433320a411b02cab414edf86a964d8c38f7bf7d","transactionHash":"0x3781d6b254e21ac0d6a0ed4b2406f2e3f49d725ac23022907e79021f2306b7ce","logs":[],"blockNumber":10314298,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x3603e4"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x59682f0a"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.6.0)
    at Logger.makeError (C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\@ethersproject\logger\src.ts\index.ts:261:28)
    at Logger.throwError (C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\@ethersproject\logger\src.ts\index.ts:273:20)
    at EthersProviderWrapper.<anonymous> (C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\@ethersproject\providers\src.ts\base-provider.ts:1523:24)
    at step (C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)
    at fulfilled (C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)
    at DeploymentsManager.executeDeployScripts (C:\Users\Nancy\hello\hh\repo\all-on-chain-generated-nft\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1014:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by PatrickAlphaC** [comment] 2022-03-14 22:23
Duplicate of: https://github.com/PatrickAlphaC/all-on-chain-generated-nft/issues/23

**Closed by PatrickAlphaC** 2022-03-14 22:23 UTC
